services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: broker
    networks:
      - app_network

  log-generator:
    build:
      context: .
      dockerfile: ./log-generator/Dockerfile
    container_name: log-generator
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: app-logs
    networks:
      - app_network
    depends_on:
      - kafka
    command: ./log-generator

  anomaly-processor:
    build:
      context: .
      dockerfile: ./anomaly-processor/Dockerfile
    container_name: anomaly-processor
    environment:
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: app-logs
      KAFKA_GROUP_ID: anomaly-processor-group
    networks:
      - app_network
    depends_on:
      - kafka
    command: ./anomaly-processor

networks:
  app_network:
    driver: bridge